name: Run Selenium Tests Daily

on:
  schedule:
    - cron: '30 10 * * *' # This cron schedule runs the workflow daily at 10:30 AM UTC (4:00 PM IST)
  workflow_dispatch: # Allows the workflow to be manually triggered

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium firebase-admin

    - name: Set up Firebase Configuration
      env:
        AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.AUTH_PROVIDER_X509_CERT_URL }}
        AUTH_URI: ${{ secrets.AUTH_URI }}
        CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_X509_CERT_URL: ${{ secrets.CLIENT_X509_CERT_URL }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
        TOKEN_URI: ${{ secrets.TOKEN_URI }}
        TYPE: ${{ secrets.TYPE }}
        UNIVERSE_DOMAIN: ${{ secrets.UNIVERSE_DOMAIN }}
        
        
        # Add other Firebase configuration secrets here
      run: |
        echo "AUTH_PROVIDER_X509_CERT_URL=$AUTH_PROVIDER_X509_CERT_URL" >> $GITHUB_ENV
        echo "AUTH_URI=$AUTH_URI" >> $GITHUB_ENV
        echo "CLIENT_EMAIL=$CLIENT_EMAIL" >> $GITHUB_ENV
        echo "CLIENT_ID=$CLIENT_ID" >> $GITHUB_ENV
        echo "CLIENT_X509_CERT_URL=$CLIENT_X509_CERT_URL" >> $GITHUB_ENV
        echo "PRIVATE_KEY=$PRIVATE_KEY" >> $GITHUB_ENV
        echo "PRIVATE_KEY_ID=$PRIVATE_KEY_ID" >> $GITHUB_ENV
        echo "TOKEN_URI=$TOKEN_URI" >> $GITHUB_ENV
        echo "TYPE=$TYPE" >> $GITHUB_ENV
        echo "UNIVERSE_DOMAIN=$UNIVERSE_DOMAIN" >> $GITHUB_ENV
        # Add other Firebase configuration here

    - name: Run Selenium Script
      env:
        SELENIUM_HOST: http://localhost:4444/wd/hub
        AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.AUTH_PROVIDER_X509_CERT_URL }}
        AUTH_URI: ${{ secrets.AUTH_URI }}
        CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_X509_CERT_URL: ${{ secrets.CLIENT_X509_CERT_URL }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
        TOKEN_URI: ${{ secrets.TOKEN_URI }}
        TYPE: ${{ secrets.TYPE }}
        UNIVERSE_DOMAIN: ${{ secrets.UNIVERSE_DOMAIN }}
      run: |
        python main.py
